# Generated by Django 5.2.2 on 2025-06-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.IntegerField()),
                ('num2', models.IntegerField()),
                ('num3', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'Processando'), ('2', 'Concluído')])),
                ('media', models.FloatField()),
                ('mediana', models.FloatField()),
            ],
        ),
    ]
