# Generated by Django 5.2.2 on 2025-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processamento',
            name='media',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='mediana',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='processamento',
            name='status',
            field=models.CharField(choices=[('1', 'Processando'), ('2', 'Concluído')], default='Processando'),
        ),
    ]
