version: '3.8'

services:
  backend:
    build: ./backend
    command: sh -c "python manage.py migrate && 
            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - db:/data/postgres
    ports:
    - 5432:5432

  worker:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq_server

  rabbitmq_server:
    image: rabbitmq:4-management
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  db: